plugins {
    id 'application'
    id 'pmd'
}

group 'com.hkupty.penna'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Reproducible builds
tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}


dependencies {
    implementation project(":penna-core")
    implementation libs.slf4j
    implementation libs.jackson.core
    implementation libs.jackson.databind
}

application {
  mainClass = "org.integration.Application"
}

run {
    jvmArgs '-ea'
}
